### PR TITLE
ApproveContent then refresh user table DiscussionCount and CommentCount

### PR DESCRIPTION
**Pull request by imzhi**
After approve the operation, update the ``discussion_count`` and ``comment_count`` fields of the ``users`` table

### CODE REVIEW

**Review by askvortsov1 — APPROVED** [review]
Looks good to me, thank you!

**Comment by clarkwinkelmann** [comment]
Would it make sense to move `$user->refreshDiscussionCount()` inside of the condition block?

The discussion count shouldn't change unless we're also approving the discussion.

This probably doesn't have a big impact but would save a database query where possible.

**Comment by askvortsov1** [comment]
Agreed.

**Comment by franzliedke** [comment]
@clarkwinkelmann Do you mean the `if ($post->number == 1)` block? That would be before the discussion save, so the result would be different, right?

**Comment by clarkwinkelmann** [comment]
Sorry I didn't reply to this right away.

Yes now that I re-read my suggestion it requires a bit more code. Essentially this:

```php
        if ($post->number == 1) {
            $discussion->is_approved = true;
        }

        $discussion->save();

        $user->refreshDiscussionCount();
        $user->refreshCommentCount();
        $user->save();
```

could be replaced with


```php
        if ($post->number == 1) {
            $discussion->is_approved = true;
        }

        $discussion->save();


        if ($post->number == 1) {
            $user->refreshDiscussionCount();
        }

        $user->refreshCommentCount();
        $user->save();
```

or

```php
        if ($post->number == 1) {
            $discussion->is_approved = true;

            $discussion->afterSave(function () use ($user) {
                $user->refreshDiscussionCount();
            });
        }

        $discussion->save();

        $user->refreshCommentCount();
        $user->save();
```

To save a database request.

Not sure if it's worth the optimization though.

**Comment by askvortsov1** [comment]
I like the second one

**Comment by askvortsov1** [comment]
@imzhi would you be interested in updating this PR as discussed above?

**Comment by imzhi** [comment]
@askvortsov1 A new commit was finished based on the discussion.

**Review by SychO9 — APPROVED** [review]

**Pull request merged**
